on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install clang-format
      - name: Run clang-format
        run: make lint
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [clang, gcc]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install build-essential valgrind ${{ matrix.cc }}
      - name: Build
        run: make CC=${{ matrix.cc }}
      - name: Unit tests
        run: ./spec.sh
